# Generated by Django 5.2.6 on 2025-09-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_name', models.CharField(blank=True, max_length=128)),
                ('current_location', models.CharField(max_length=256)),
                ('pickup_location', models.CharField(max_length=256)),
                ('dropoff_location', models.CharField(max_length=256)),
                ('current_cycle_used_hours', models.FloatField(default=0.0)),
                ('plan_result', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
